name: Update Gulpase Index on Jira

on:
  push:
    branches:
      - main
      # - setup-gulpase-action
  workflow_dispatch:

jobs:
  gulpease-update: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup enviroment
        uses: ./.github/actions/setup-docs-env

      - name: Build all baseline docs
        run: notipdo build baseline
      
      - name: Calulate Gulpease index
        run: notipdo metrics gulpease
      
      # Add the actual update of the values in Jira