name: Update Gulpase Index on Jira

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gulpease-update: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup environment
        uses: ./.github/actions/setup-docs-env

      - name: Build all baseline docs
        run: notipdo build baseline
      
      - name: Calculate Gulpease index and Send to Jira
        # Passiamo i secret come variabili d'ambiente
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_ISSUE_KEY: ${{ secrets.JIRA_ISSUE_KEY }}
          JIRA_CUSTOM_FIELD_ID: ${{ secrets.JIRA_CUSTOM_FIELD_ID }}
        run: notipdo metrics gulpease --jira